"""Plugin integrity verification: SHA-256 manifest of plugin files, regenerated by CI.

In Zero-Trust mode, the SessionStart hook verifies that every shipped plugin file
matches the hash in ``MANIFEST.lock`` before doing anything. Mismatch = fail-closed
(no hooks fire, audit logged) so a tampered plugin can't run silently.

CLI::

    python lib/integrity.py --write     # regenerate MANIFEST.lock
    python lib/integrity.py --verify    # verify; exit 1 on mismatch
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections.abc import Iterable
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = PLUGIN_ROOT / "MANIFEST.lock"

# Files included in the integrity manifest. Anything that affects hook behavior
# or plugin distribution metadata.
_INCLUDE_GLOBS = (
    ".claude-plugin/plugin.json",
    ".claude-plugin/marketplace.json",
    "hooks/hooks.json",
    "hooks/scripts/*.sh",
    "lib/*.py",
    "skills/**/*.md",
    "agents/*.md",
    "commands/*.md",
    "presets/*.json",
    "presets/redaction/*.json",
)
# Things never included: tests, docs, README, LICENSE (these don't affect runtime).


def _iter_tracked(root: Path) -> Iterable[Path]:
    seen: set[Path] = set()
    for pattern in _INCLUDE_GLOBS:
        for p in sorted(root.glob(pattern)):
            if p.is_file() and p not in seen:
                seen.add(p)
                yield p


def _hash_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def compute_manifest(root: Path | None = None) -> dict[str, str]:
    """Return ``{relative_posix_path: sha256_hex}`` for every tracked file."""
    root = root or PLUGIN_ROOT
    out: dict[str, str] = {}
    for p in _iter_tracked(root):
        rel = p.relative_to(root).as_posix()
        out[rel] = _hash_file(p)
    return out


def write_manifest(root: Path | None = None) -> Path:
    root = root or PLUGIN_ROOT
    manifest = {
        "_format": 1,
        "files": compute_manifest(root),
    }
    target = root / "MANIFEST.lock"
    target.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return target


def load_manifest(root: Path | None = None) -> dict[str, str] | None:
    root = root or PLUGIN_ROOT
    p = root / "MANIFEST.lock"
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text())
    except json.JSONDecodeError:
        return None
    files = data.get("files")
    return files if isinstance(files, dict) else None


def verify_manifest(root: Path | None = None) -> tuple[list[str], list[str], list[str]]:
    """Return (missing, mismatched, extra) relative paths."""
    root = root or PLUGIN_ROOT
    declared = load_manifest(root)
    if declared is None:
        return ([], [], [])  # no manifest -> nothing to verify (caller decides policy)
    actual = compute_manifest(root)
    missing = [p for p in declared if p not in actual]
    mismatched = [p for p in declared if p in actual and actual[p] != declared[p]]
    extra = [p for p in actual if p not in declared]
    return (missing, mismatched, extra)


def integrity_ok(root: Path | None = None) -> bool:
    # Extra files count as failure: an undeclared file under the tracked globs
    # (e.g. a dropped lib/*.py) would shadow a real import via PYTHONPATH, so a
    # tampered plugin must not pass by addition any more than by modification.
    missing, mismatched, extra = verify_manifest(root)
    return not missing and not mismatched and not extra


def _cli() -> int:
    ap = argparse.ArgumentParser(description="presence plugin integrity tool")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true", help="regenerate MANIFEST.lock")
    g.add_argument("--verify", action="store_true", help="verify against MANIFEST.lock")
    g.add_argument(
        "--audit-verify", action="store_true",
        help="walk the audit log hash chain and report any tampered or broken-link lines",
    )
    ap.add_argument("--root", type=Path, default=PLUGIN_ROOT)
    args = ap.parse_args()

    if args.write:
        target = write_manifest(args.root)
        print(f"wrote {target}")
        return 0

    if args.audit_verify:
        from audit import verify_chain
        report = verify_chain()
        if not report["exists"]:
            print("no audit log present (~/.claude/presence/audit.jsonl)")
            return 0
        print(f"audit log: {report['lines']} line(s)")
        if report["corrupt"]:
            print(f"  corrupt   : {len(report['corrupt'])} line(s) at indices {report['corrupt'][:10]}")
        if report["tampered"]:
            print(f"  TAMPERED  : {len(report['tampered'])} line(s) at indices {report['tampered'][:10]}")
        if report["broken_link"]:
            print(f"  broken    : {len(report['broken_link'])} hash-chain link(s) at {report['broken_link'][:10]}")
        if report["ok"]:
            print("audit chain OK")
            return 0
        return 1

    declared = load_manifest(args.root)
    if declared is None:
        print("no MANIFEST.lock present")
        return 1
    missing, mismatched, extra = verify_manifest(args.root)
    if missing:
        print("missing files (declared but absent):")
        for p in missing:
            print(f"  {p}")
    if mismatched:
        print("mismatched files (hash differs):")
        for p in mismatched:
            print(f"  {p}")
    if extra:
        print(f"extra files not in manifest ({len(extra)}):")
        for p in extra[:10]:
            print(f"  {p}")
        if len(extra) > 10:
            print(f"  ... and {len(extra) - 10} more")
    if missing or mismatched:
        return 1
    print("integrity OK")
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
